# Generated by Django 3.2.7 on 2021-10-18 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, verbose_name='Apartment booking')),
                ('description', models.TextField(max_length=700, verbose_name='Apartment booking')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MinValueValidator(100000)], verbose_name='price')),
            ],
        ),
    ]
